import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Blocks, Database, Fingerprint, Gauge, Landmark, Network, ScanFace, ShieldCheck, Wrench } from "lucide-react";
import { approach, expertises, news, timeline } from "@/data/homepage";
import { Container, PrimaryButton, SecondaryButton, SectionHeading } from "@/components/shared/HomeUI";
import { AnimatedDataLines } from "@/components/visuals/AfricaNetworkVisual";
import SolutionsSection from "./SolutionsSection";

const expertiseIcons=[Network,Database,Fingerprint,Blocks,ShieldCheck,Gauge,Wrench];

export function HeroSection(){return <section className="sovereign-hero image-hero"><Image className="hero-photo" src="/images/aba/home/aba-operations-hero.png" alt="Expert congolais supervisant une solution technologique et biométrique" fill priority sizes="100vw"/><div className="hero-photo-overlay"/><AnimatedDataLines/><Container className="hero-layout"><div className="sovereign-copy"><span className="hero-eyebrow"><i/>Entreprise congolaise de souveraineté numérique</span><h1>Nous bâtissons la souveraineté numérique et technologique des institutions africaines.</h1><p>Africa Business Agency conçoit, développe, intègre et déploie des systèmes d’information, des solutions biométriques et des technologies sécurisées adaptées aux enjeux stratégiques des États et des grandes organisations.</p><div className="hero-actions"><PrimaryButton href="/institution">Découvrir ABA</PrimaryButton><SecondaryButton href="/contact" light>Parler à un expert</SecondaryButton></div><div className="hero-signature">Audit <i/> Conseil <i/> Développement <i/> Intégration <i/> Déploiement <i/> Maintenance</div><span className="made-label">Made in DRC</span></div></Container></section>}

export function InstitutionalTrustBar(){const items=[[ShieldCheck,"Souveraineté des données","Garder la maîtrise des actifs stratégiques."],[ScanFace,"Sécurité des systèmes","Protéger les usages et la continuité."],[Network,"Interopérabilité","Faire dialoguer les systèmes avec cohérence."],[Landmark,"Déploiement à grande échelle","Passer de la conception à l’usage terrain."]] as const;return <section className="trust-bar"><Container><h2>Des solutions technologiques conçues pour les environnements institutionnels critiques.</h2><div>{items.map(([Icon,title,text])=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></Container></section>}

export function AboutABASection(){return <section className="aba-section about-aba"><Container className="about-layout"><div><SectionHeading eyebrow="Africa Business Agency" title="Une entreprise congolaise au service de la souveraineté numérique."/><p>Fondée en 2013, Africa Business Agency accompagne les institutions publiques, les forces de défense et de sécurité ainsi que les grandes organisations dans leur transformation numérique.</p><p>ABA conçoit des solutions sécurisées et adaptées aux réalités opérationnelles, en combinant audit, développement logiciel, intégration de systèmes, fourniture d’équipements, formation et maintenance.</p><PrimaryButton href="/institution">Découvrir notre histoire</PrimaryButton></div><div><div className="about-photo"><Image src="/images/aba/expertises/biometrie/hero.webp" alt="Opération d’enrôlement biométrique conduite par un spécialiste africain" fill sizes="(max-width: 900px) 100vw, 50vw"/></div><div className="about-facts">{["Fondée en 2013","Entreprise congolaise","Ingénieurs et développeurs congolais","Solutions conçues en RDC","Intervention institutionnelle","Approche intégrée"].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></div></Container></section>}

const expertiseImages=["/images/aba/expertises/plateformes-metier.webp","/images/aba/expertises/gouvernance-donnees.webp","/images/aba/expertises/biometrie/hero.webp","/images/aba/expertises/transformation-institutionnelle.webp","/images/aba/expertises/securite-si.webp","/images/aba/projects/audit-base-institutionnelle.webp","/images/aba/expertises/deploiement-supervision.webp"];
export function ExpertiseCard({item,index}:{item:(typeof expertises)[number];index:number}){const Icon=expertiseIcons[index];return <article className="expertise-card-new"><div className="expertise-photo"><Image src={expertiseImages[index]} alt="" fill sizes="(max-width: 600px) 100vw, 33vw"/><span/></div><div className="expertise-card-head"><span>0{index+1}</span><Icon/></div><h3>{item[0]}</h3><p>{item[1]}</p><Link href="/expertises">En savoir plus <ArrowRight size={16}/></Link></article>}
export function ExpertiseSection(){return <section className="aba-section expertise-section-new" id="expertises"><Container><SectionHeading light eyebrow="Nos domaines d’expertise" title="Une expertise intégrée pour les projets numériques stratégiques." copy="De la donnée aux opérations, ABA réunit les compétences nécessaires à la construction de systèmes institutionnels fiables."/><div className="expertise-grid-new">{expertises.map((x,i)=><ExpertiseCard item={x} index={i} key={x[0]}/>)}</div></Container></section>}

export function IntegratedApproachSection(){return <section className="aba-section approach-section"><Container><SectionHeading eyebrow="Approche intégrée ABA" title="Une maîtrise complète du cycle de transformation numérique."/><ol>{approach.map(([title,text],i)=><li key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></Container></section>}

export function TimelineSection(){return <section className="aba-section timeline-section" id="realisations"><Container><SectionHeading eyebrow="Parcours & réalisations" title="Plus d’une décennie de réalisations au service des institutions."/><div className="institutional-timeline">{timeline.map(([year,title,text])=><article key={year}><time>{year}</time><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><SecondaryButton href="/projets">Découvrir nos réalisations</SecondaryButton></Container></section>}

export function MadeInDRCSection(){const pillars=[["Expertise locale","Des équipes congolaises capables de comprendre les réalités administratives, techniques et opérationnelles du terrain."],["Maîtrise technologique","Une capacité interne de conception, de développement, d’intégration et de maintenance."],["Souveraineté","Des solutions favorisant la maîtrise institutionnelle des données, des systèmes et des infrastructures."],["Durabilité","Des plateformes évolutives accompagnées par la formation, l’assistance technique et la maintenance."]];return <section className="aba-section drc-section"><Container><span className="drc-stamp">Made in DRC</span><SectionHeading eyebrow="Valeur ajoutée" title="Des solutions pensées, développées et déployées en République démocratique du Congo."/><div>{pillars.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></Container></section>}

export function VisionSection(){return <section className="vision-section vision-image"><Image src="/images/military-it-professional-gathers-intelligence-from-world-map-projection.jpg" alt="Professionnel africain supervisant un réseau numérique stratégique" fill sizes="100vw"/><div className="vision-overlay"/><Container><div><span>Notre vision</span><h2>L’innovation au service de la sécurité, de la gouvernance et du développement.</h2><p>Africa Business Agency contribue au renforcement de la souveraineté numérique des États africains en développant des solutions technologiques sécurisées, performantes et adaptées aux besoins institutionnels.</p></div></Container></section>}

export function NewsSection(){return <section className="aba-section news-section"><Container><SectionHeading eyebrow="Publications" title="Actualités et perspectives."/><div>{news.map(item=><article key={item.title}><header><span>{item.category}</span><time>{item.date}</time></header><h3>{item.title}</h3><p>{item.summary}</p><Link href="/actualites">Lire l’article <ArrowRight size={16}/></Link></article>)}</div></Container></section>}

export function FinalCTA(){return <section className="final-cta"><AnimatedDataLines/><Container><span>Un projet stratégique ?</span><h2>Construisons ensemble des systèmes numériques souverains et durables.</h2><p>Parlez-nous de vos enjeux institutionnels, technologiques ou opérationnels. Nos équipes vous accompagnent de l’audit initial au déploiement et à la maintenance.</p><div><PrimaryButton href="/contact">Parler à un expert</PrimaryButton><SecondaryButton href="/contact" light>Nous contacter</SecondaryButton></div></Container></section>}

export default function HomeSections(){return <><HeroSection/><InstitutionalTrustBar/><AboutABASection/><ExpertiseSection/><IntegratedApproachSection/><TimelineSection/><SolutionsSection/><MadeInDRCSection/><VisionSection/><NewsSection/><FinalCTA/></>}
