import { requireAdmin } from "@/lib/admin-auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import AdminDashboard from "@/components/admin/AdminDashboard";

export const adminModules=["projects","tasks","submissions","activity","calendar","notes","cards","mail","contents","services","media","documents","users"] as const;
export type AdminModule="overview"|(typeof adminModules)[number];

export async function renderAdminDashboard(view:AdminModule="overview"){
  const {profile,supabase}=await requireAdmin();
  const [servicesResult,contentResult,mediaResult,documentsResult,profilesResult,projectsResult,eventsResult,notesResult,cardsResult,mailsResult,tasksResult,submissionsResult,commentsResult,checklistResult,activityResult,membersResult,conversationsResult,chatResult]=await Promise.all([
    supabase.from("service_cards").select("*").order("position"),supabase.from("content_entries").select("*").order("page").order("section"),supabase.from("media_assets").select("*").order("created_at",{ascending:false}),supabase.from("document_assets").select("*").order("created_at",{ascending:false}),supabase.from("profiles").select("*").order("created_at",{ascending:false}),supabase.from("projects").select("*").order("created_at",{ascending:false}),supabase.from("calendar_events").select("*").gte("starts_at",new Date(new Date().setHours(0,0,0,0)).toISOString()).order("starts_at").limit(50),supabase.from("staff_notes").select("*").order("created_at",{ascending:false}).limit(50),supabase.from("print_cards").select("*").order("created_at",{ascending:false}),supabase.from("mail_messages").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("project_tasks").select("*").order("position").order("created_at"),supabase.from("project_submissions").select("*").order("created_at",{ascending:false}),supabase.from("project_comments").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("task_checklist_items").select("*").order("position").order("created_at"),supabase.from("activity_log").select("*").order("created_at",{ascending:false}).limit(50),supabase.from("project_members").select("*").order("created_at"),supabase.from("conversations").select("*").order("updated_at",{ascending:false}),supabase.from("chat_messages").select("*").order("created_at").limit(500)
  ]);
  let users=(profilesResult.data||[]).map(item=>({...item,email:""}));
  if(profile.role==="admin"&&process.env.SUPABASE_SERVICE_ROLE_KEY){const admin=createSupabaseAdminClient();const {data}=await admin.auth.admin.listUsers({perPage:100});const emails=new Map(data.users.map(user=>[user.id,user.email||""]));users=users.map(item=>({...item,email:emails.get(item.id)||""}))}
  const setupError=servicesResult.error||contentResult.error||mediaResult.error||projectsResult.error;
  return <AdminDashboard view={view} currentUserId={profile.id} services={servicesResult.data||[]} contents={contentResult.data||[]} media={mediaResult.data||[]} documents={documentsResult.data||[]} users={users} members={membersResult.data||[]} conversations={conversationsResult.data||[]} chatMessages={chatResult.data||[]} isAdmin={profile.role==="admin"} role={profile.role} projects={projectsResult.data||[]} tasks={tasksResult.data||[]} submissions={submissionsResult.data||[]} comments={commentsResult.data||[]} checklist={checklistResult.data||[]} activity={activityResult.data||[]} events={eventsResult.data||[]} notes={notesResult.data||[]} cards={cardsResult.data||[]} mails={mailsResult.data||[]} setupError={setupError?.message||""}/>;
}
