"use client";
import {useState} from "react";
import type {CardRequest} from "@/types/identity-studio-card-request";
const labels={soumise:"Nouvelle",en_verification:"À vérifier",approuvee:"Approuvée",rejetee:"Rejetée",imprimee:"Imprimée"};
export default function AdminIdentityStudioWorkspace({requests,initialSelected}:{requests:CardRequest[];initialSelected?:string}){
  const ordered=[...requests].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());
  const [selected,setSelected]=useState(ordered.some(item=>item.id===initialSelected)?initialSelected!:ordered[0]?.id||""),[busy,setBusy]=useState(false);const current=ordered.find(item=>item.id===selected);
  async function update(action:string){if(!current)return;setBusy(true);await fetch(`/api/admin/card-requests/${current.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});setBusy(false);window.location.reload()}
  return <div className="admin-identity-page">
    <header className="admin-topbar"><div><small>OUTIL INTÉGRÉ</small><h1>ABA Identity Studio</h1></div><div className="identity-top-actions"><a className="share" href="/demande-carte" target="_blank">Créer une carte ↗</a><a className="share" href="/signature-professionnelle" target="_blank">Créer une signature ↗</a><a href={`/identity-studio${selected?`?request=${selected}&type=${current?.card_type||"service"}`:""}`} target="_blank">Plein écran ↗</a></div></header>
    <section className="identity-request-bar"><div><strong>Demandes reçues</strong><span>{ordered.length} dossier{ordered.length!==1?"s":""} · plus récentes en premier</span></div>{ordered.length?<div className="identity-status-actions"><button disabled={busy} onClick={()=>update("verify")}>Vérifier</button><button disabled={busy} onClick={()=>update("approve")}>Approuver</button><button disabled={busy} onClick={()=>update("reject")}>Rejeter</button><button disabled={busy} onClick={()=>update("printed")}>Imprimée</button></div>:<p>Aucune demande reçue. Partagez le formulaire public.</p>}</section>
    <div className="identity-studio-workspace"><aside className="identity-queue-column"><div className="identity-queue-summary"><span><b>{ordered.filter(item=>item.status==="soumise").length}</b>Nouvelles</span><span><b>{ordered.filter(item=>item.card_type==="service").length}</b>Service</span><span><b>{ordered.filter(item=>item.card_type==="visite").length}</b>Visite</span></div>{ordered.length>0&&<section className="identity-request-list" aria-label="Liste ordonnée des demandes">{ordered.map((item,index)=><button className={selected===item.id?"active":""} onClick={()=>setSelected(item.id)} key={item.id}><b>{String(index+1).padStart(2,"0")}</b><span><strong>{item.first_name} {item.middle_name} {item.last_name}</strong><small>{item.matricule} · {item.card_type==="visite"?"Carte de visite":"Carte de service"}</small></span><i className={`request-state ${item.status}`}>{labels[item.status]}</i><time>{new Date(item.created_at).toLocaleDateString("fr-FR",{day:"2-digit",month:"short",year:"numeric"})}</time></button>)}</section>}{current&&<section className="identity-request-details"><span><b>{current.first_name} {current.middle_name} {current.last_name}</b>{current.job_title}</span><span><b>{current.email}</b>{current.phone}</span><span><b>{current.department||"Sans département"}</b>{new Date(current.created_at).toLocaleDateString("fr-FR")}</span></section>}</aside><iframe key={`${selected}-${current?.card_type}`} className="admin-identity-frame" src={`/identity-studio${selected?`?request=${selected}&type=${current?.card_type||"service"}`:""}`} title="ABA Identity Studio" allow="clipboard-write"/></div>
  </div>
}
