"use client";

import { useState, useTransition } from "react";
import { createConversationAction, createProjectMemberAction, saveEventAction, saveNoteAction, savePrintCardAction, saveProjectAction, saveTaskAction, sendChatMessageAction, sendEmailAction, updateProjectProgressAction, updateSubmissionStatusAction, updateTaskStatusAction, updateWhatsAppPreferenceAction, type ActionResult } from "@/app/admin/actions";

type Project = { id:string; name:string; description:string; status:string; priority:string; progress:number; due_date:string|null;owner_id:string|null;repository_url:string|null };
type Event = { id:string; title:string; description:string; starts_at:string; location:string; event_type:string };
type Note = { id:string; title:string; body:string; visibility:string; created_at:string };
type Card = { id:string; card_number:string; holder_name:string; holder_role:string; department:string; service_name:string; valid_until:string|null; photo_url:string|null; status:string };
type Mail = { id:string; direction:string; sender:string; recipient:string; subject:string; body:string; status:string; created_at:string };
type Task={id:string;project_id:string;title:string;description:string;status:string;priority:string;due_date:string|null};
type Submission={id:string;organization:string;contact_name:string;phone:string;title:string;project_type:string;description:string;budget_range:string;status:string;created_at:string};
type Comment={id:string;project_id:string;task_id:string|null;body:string;created_at:string};
type Checklist={id:string;task_id:string;label:string;completed:boolean};
type Activity={id:string;entity_type:string;action:string;details:Record<string,unknown>;created_at:string};
type User={id:string;full_name:string;role:string;email?:string;whatsapp_phone?:string|null;whatsapp_opt_in?:boolean};type Member={project_id:string;user_id:string;project_role:string};
type Conversation={id:string;conversation_type:string;title:string;project_id:string|null;updated_at:string};type ChatMessage={id:string;conversation_id:string;sender_id:string;body:string;created_at:string};
type Dialog = "project"|"member"|"task"|"event"|"note"|"card"|"mail"|"conversation"|null;

const statusLabel: Record<string,string> = { planifie:"Planifié", en_cours:"En cours", bloque:"Bloqué", termine:"Terminé", sent:"Envoyé", queued:"En attente", received:"Reçu", failed:"Échec" };

export default function AdminOperations({ view="overview",currentUserId,role,users,members,conversations,chatMessages,projects, tasks, submissions, comments, checklist, activity, events, notes, cards, mails, canManage }: { view?:string;currentUserId:string;role:string;users:User[];members:Member[];conversations:Conversation[];chatMessages:ChatMessage[];projects:Project[]; tasks:Task[]; submissions:Submission[]; comments:Comment[]; checklist:Checklist[]; activity:Activity[]; events:Event[]; notes:Note[]; cards:Card[]; mails:Mail[]; canManage:boolean }) {
  const [dialog,setDialog]=useState<Dialog>(null); const [memberProject,setMemberProject]=useState("");const [selectedConversation,setSelectedConversation]=useState(conversations[0]?.id||"");const [notice,setNotice]=useState<ActionResult|null>(null); const [pending,startTransition]=useTransition();
  const run=(action:()=>Promise<ActionResult>)=>startTransition(async()=>{const result=await action();setNotice(result);if(result.ok){setDialog(null);setTimeout(()=>window.location.reload(),450)}});
  const submit=(event:React.FormEvent<HTMLFormElement>,action:(data:FormData)=>Promise<ActionResult>)=>{event.preventDefault();run(()=>action(new FormData(event.currentTarget)))};
  return <div className="admin-operations-root" data-module={view}>
    {notice&&<div className={`admin-toast ${notice.ok?"success":"error"}`}>{notice.message}<button onClick={()=>setNotice(null)}>×</button></div>}

    <section id="projects" className="admin-panel admin-operations-panel"><PanelHead title="Gestion de projets" subtitle="Chef de projet, équipe dédiée, priorités et échéances" action={canManage?"Nouveau projet":undefined} onClick={()=>setDialog("project")}/>
      <div className="admin-project-board">{projects.map(project=>{const team=members.filter(member=>member.project_id===project.id);const leader=users.find(person=>person.id===project.owner_id);return <article key={project.id}><header><span className={`priority ${project.priority}`}>{project.priority}</span><small>{statusLabel[project.status]||project.status}</small></header><h3>{project.name}</h3><p>{project.description||"Aucune description"}</p>{project.repository_url&&<a className="project-repository" href={project.repository_url} target="_blank" rel="noreferrer">Voir le dépôt GitHub ↗</a>}<div className="project-lead"><span>CHEF DE PROJET</span><strong>{leader?.full_name||"À désigner"}</strong></div><div className="project-team"><div>{team.slice(0,5).map(member=>{const person=users.find(item=>item.id===member.user_id);return <span title={person?.full_name||"Membre"} key={member.user_id}>{(person?.full_name||"EX").split(" ").map(v=>v[0]).slice(0,2).join("")}</span>})}</div><small>{team.length} membre{team.length>1?"s":""}</small>{["admin","direction","chef_projet"].includes(role)&&<button onClick={()=>{setMemberProject(project.id);setDialog("member")}}>+ Ajouter</button>}</div><div className="project-metrics"><span>{tasks.filter(task=>task.project_id===project.id).length} tâches</span><span>{comments.filter(comment=>comment.project_id===project.id).length} échanges</span></div><div className="project-progress"><span><i style={{width:`${project.progress}%`}}/></span><strong>{project.progress}%</strong></div><footer><small>{project.due_date?`Échéance ${new Date(project.due_date).toLocaleDateString("fr-FR")}`:"Sans échéance"}</small><select aria-label={`Avancement de ${project.name}`} value={project.progress} onChange={e=>run(()=>updateProjectProgressAction(project.id,Number(e.target.value)))}>{[0,25,50,75,100].map(value=><option key={value} value={value}>{value}%</option>)}</select></footer></article>})}{!projects.length&&<Empty text="Aucun projet disponible."/>}</div>
    </section>

    <section id="tasks" className="admin-panel"><PanelHead title="Tableau des tâches" subtitle="Flux Kanban : à faire, en cours et terminé" action="Nouvelle tâche" onClick={()=>setDialog("task")}/><div className="admin-kanban">{[["a_faire","À faire"],["en_cours","En cours"],["termine","Terminé"]].map(([status,label])=><div className="kanban-column" key={status}><header><strong>{label}</strong><span>{tasks.filter(task=>task.status===status).length}</span></header>{tasks.filter(task=>task.status===status).map(task=>{const items=checklist.filter(item=>item.task_id===task.id);return <article key={task.id}><span className={`priority ${task.priority}`}>{task.priority}</span><h3>{task.title}</h3><p>{task.description||projects.find(project=>project.id===task.project_id)?.name}</p>{items.length>0&&<div className="task-check-progress">✓ {items.filter(item=>item.completed).length}/{items.length} sous-tâches</div>}<footer><small>{task.due_date?new Date(task.due_date).toLocaleDateString("fr-FR"):"Sans échéance"}</small><select value={task.status} onChange={e=>run(()=>updateTaskStatusAction(task.id,e.target.value))}><option value="a_faire">À faire</option><option value="en_cours">En cours</option><option value="termine">Terminé</option></select></footer></article>})}</div>)}</div></section>

    <section id="activity" className="admin-panel"><PanelHead title="Activité récente" subtitle="Traçabilité des actions de l’équipe" onClick={()=>{}}/><div className="admin-activity">{activity.map(item=><article key={item.id}><span>{item.entity_type.slice(0,1).toUpperCase()}</span><div><strong>{item.action.replaceAll("_"," ")}</strong><small>{typeof item.details?.excerpt==="string"?item.details.excerpt:"Mise à jour enregistrée"}</small></div><time>{new Date(item.created_at).toLocaleString("fr-FR")}</time></article>)}{!activity.length&&<Empty text="L’activité apparaîtra ici."/>}</div></section>

    <section id="submissions" className="admin-panel"><PanelHead title="Demandes externes" subtitle="Projets déposés par les visiteurs" onClick={()=>{}}/><div className="admin-submissions">{submissions.map(item=><article key={item.id}><header><span>{item.project_type.replaceAll("_"," ")}</span><time>{new Date(item.created_at).toLocaleDateString("fr-FR")}</time></header><h3>{item.title}</h3><strong>{item.organization} · {item.contact_name}</strong><p>{item.description}</p><footer><small>{item.phone||"Téléphone non renseigné"} · Budget {item.budget_range.replaceAll("_"," ")}</small><select value={item.status} onChange={e=>run(()=>updateSubmissionStatusAction(item.id,e.target.value))}><option value="soumis">Soumis</option><option value="en_etude">En étude</option><option value="rendez_vous">Rendez-vous</option><option value="accepte">Accepté</option><option value="refuse">Non retenu</option></select></footer></article>)}{!submissions.length&&<Empty text="Aucune demande externe reçue."/>}</div></section>

    <div className="admin-ops-grid">
      <section id="calendar" className="admin-panel"><PanelHead title="Calendrier" subtitle="Réunions et échéances" action="Ajouter" onClick={()=>setDialog("event")}/><div className="admin-agenda">{events.map(item=><article key={item.id}><time><b>{new Date(item.starts_at).toLocaleDateString("fr-FR",{day:"2-digit"})}</b><span>{new Date(item.starts_at).toLocaleDateString("fr-FR",{month:"short"})}</span></time><div><small>{item.event_type} · {new Date(item.starts_at).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}</small><strong>{item.title}</strong><span>{item.location||"En ligne / à définir"}</span></div></article>)}{!events.length&&<Empty text="Aucun événement à venir."/>}</div></section>
      <section id="notes" className="admin-panel"><PanelHead title="Notes d’équipe" subtitle="Informations internes" action="Nouvelle note" onClick={()=>setDialog("note")}/><div className="admin-notes">{notes.map(note=><article key={note.id}><span>{note.visibility}</span><h3>{note.title}</h3><p>{note.body}</p><small>{new Date(note.created_at).toLocaleDateString("fr-FR")}</small></article>)}{!notes.length&&<Empty text="Aucune note partagée."/>}</div></section>
    </div>

    <section id="cards" className="admin-panel"><PanelHead title="Cartes de service" subtitle="Badges professionnels prêts pour impression" action={canManage?"Créer une carte":undefined} onClick={()=>setDialog("card")}/><div className="admin-print-grid">{cards.map(card=><article className="print-card" key={card.id}><div className="print-card-brand"><strong>ABA</strong><span>AFRICA BUSINESS AGENCY</span></div><div className="print-card-body">{card.photo_url?<img src={card.photo_url} alt=""/>:<div className="print-card-avatar">{card.holder_name.split(" ").map(v=>v[0]).slice(0,2).join("")}</div>}<div><small>{card.service_name}</small><h3>{card.holder_name}</h3><p>{card.holder_role}</p><span>{card.department}</span></div></div><footer><div><small>N° CARTE</small><strong>{card.card_number}</strong></div><div><small>VALIDITÉ</small><strong>{card.valid_until?new Date(card.valid_until).toLocaleDateString("fr-FR"):"PERMANENTE"}</strong></div><button onClick={()=>window.print()}>Imprimer</button></footer></article>)}{!cards.length&&<Empty text="Aucune carte de service créée."/>}</div></section>

    <section id="mail" className="admin-panel"><PanelHead title="Communications ABA" subtitle="Projets, messages privés, groupes, e-mail et notifications WhatsApp" action="Nouvelle discussion" onClick={()=>setDialog("conversation")}/><div className="admin-chat-layout"><aside><div className="chat-list-head"><strong>Discussions</strong><button onClick={()=>setDialog("mail")}>+ E-mail</button></div>{conversations.map(conversation=><button className={selectedConversation===conversation.id?"active":""} onClick={()=>setSelectedConversation(conversation.id)} key={conversation.id}><i>{conversation.conversation_type==="project"?"▦":conversation.conversation_type==="group"?"♙":"●"}</i><span><strong>{conversation.title||"Conversation privée"}</strong><small>{conversation.conversation_type}</small></span></button>)}</aside><div className="chat-room">{selectedConversation?<><header><div><strong>{conversations.find(item=>item.id===selectedConversation)?.title||"Conversation privée"}</strong><small>Communication sécurisée ABA</small></div></header><div className="chat-messages">{chatMessages.filter(message=>message.conversation_id===selectedConversation).map(message=>{const author=users.find(item=>item.id===message.sender_id);return <article className={message.sender_id===currentUserId?"mine":""} key={message.id}><small>{author?.full_name||"Utilisateur"}</small><p>{message.body}</p><time>{new Date(message.created_at).toLocaleString("fr-FR")}</time></article>})}</div><form className="chat-composer" onSubmit={e=>submit(e,sendChatMessageAction)}><input type="hidden" name="conversation_id" value={selectedConversation}/><textarea name="body" rows={2} placeholder="Écrire un message…" required/><button disabled={pending}>Envoyer</button></form></>:<Empty text="Créez ou sélectionnez une discussion."/>}</div></div><div className="communication-tools"><form onSubmit={e=>submit(e,updateWhatsAppPreferenceAction)}><div><strong>WhatsApp obligatoire</strong><small>Chaque message déclenche une notification WhatsApp et un e-mail ABA.</small></div><input name="whatsapp_phone" placeholder="+243…" required defaultValue={users.find(item=>item.id===currentUserId)?.whatsapp_phone||""}/><span className="whatsapp-required">Notifications toujours actives</span><button>Enregistrer</button></form></div><details className="admin-email-archive"><summary>E-mails envoyés et reçus ({mails.length})</summary><div className="admin-mail-list">{mails.map(mail=><article key={mail.id}><span className={`mail-direction ${mail.direction}`}>{mail.direction==="inbound"?"↓":"↑"}</span><div><strong>{mail.subject}</strong><small>{mail.direction==="inbound"?mail.sender:mail.recipient}</small></div><span className={`status ${mail.status}`}>{statusLabel[mail.status]||mail.status}</span><time>{new Date(mail.created_at).toLocaleDateString("fr-FR")}</time></article>)}</div></details></section>

    {dialog&&<div className="admin-modal-backdrop" onMouseDown={()=>setDialog(null)}><div className="admin-modal" onMouseDown={e=>e.stopPropagation()}><button className="admin-modal-close" onClick={()=>setDialog(null)}>×</button>
      {dialog==="project"&&<Form title="Nouveau projet" onSubmit={e=>submit(e,saveProjectAction)} pending={pending}><Field label="Nom du projet"><input name="name" required/></Field><Field label="Description"><textarea name="description" rows={4}/></Field><Field label="Dépôt GitHub"><input name="repository_url" type="url" placeholder="https://github.com/organisation/projet"/></Field><Field label="Chef de projet"><select name="owner_id"><option value="">Moi-même</option>{users.filter(person=>["admin","direction","personnel","chef_projet"].includes(person.role)).map(person=><option key={person.id} value={person.id}>{person.full_name} · {person.role}</option>)}</select></Field><div className="admin-form-row"><Field label="Statut"><select name="status"><option value="planifie">Planifié</option><option value="en_cours">En cours</option><option value="bloque">Bloqué</option></select></Field><Field label="Priorité"><select name="priority"><option value="normale">Normale</option><option value="haute">Haute</option><option value="critique">Critique</option><option value="basse">Basse</option></select></Field></div><Field label="Échéance"><input name="due_date" type="date"/></Field></Form>}
      {dialog==="member"&&<Form title="Ajouter un membre externe" onSubmit={e=>submit(e,createProjectMemberAction)} pending={pending}><input type="hidden" name="project_id" value={memberProject}/><Field label="Nom complet"><input name="full_name" required/></Field><div className="admin-form-row"><Field label="Adresse e-mail"><input name="email" type="email" required/></Field><Field label="WhatsApp obligatoire"><input name="whatsapp_phone" type="tel" placeholder="+243…" required/></Field></div><Field label="Mot de passe temporaire"><input name="password" placeholder="Généré automatiquement si vide" minLength={8}/></Field><div className="member-access-note"><strong>Accès limité</strong><span>Cette personne verra uniquement ce projet. Chaque notification lui sera envoyée par WhatsApp et par e-mail.</span></div></Form>}
      {dialog==="task"&&<Form title="Nouvelle tâche" onSubmit={e=>submit(e,saveTaskAction)} pending={pending}><Field label="Projet"><select name="project_id" required><option value="">Sélectionner</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></Field><Field label="Titre"><input name="title" required/></Field><Field label="Description"><textarea name="description" rows={4}/></Field><div className="admin-form-row"><Field label="Priorité"><select name="priority"><option value="normale">Normale</option><option value="haute">Haute</option><option value="critique">Critique</option><option value="basse">Basse</option></select></Field><Field label="Échéance"><input name="due_date" type="date"/></Field></div></Form>}
      {dialog==="event"&&<Form title="Nouvel événement" onSubmit={e=>submit(e,saveEventAction)} pending={pending}><Field label="Titre"><input name="title" required/></Field><div className="admin-form-row"><Field label="Début"><input name="starts_at" type="datetime-local" required/></Field><Field label="Fin"><input name="ends_at" type="datetime-local"/></Field></div><Field label="Lieu"><input name="location"/></Field><Field label="Description"><textarea name="description" rows={3}/></Field></Form>}
      {dialog==="note"&&<Form title="Nouvelle note" onSubmit={e=>submit(e,saveNoteAction)} pending={pending}><Field label="Titre"><input name="title" required/></Field><Field label="Note"><textarea name="body" rows={6}/></Field><Field label="Visibilité"><select name="visibility"><option value="equipe">Toute l’équipe</option><option value="direction">Direction</option><option value="privee">Privée</option></select></Field></Form>}
      {dialog==="card"&&<Form title="Carte de service" onSubmit={e=>submit(e,savePrintCardAction)} pending={pending}><div className="admin-form-row"><Field label="Titulaire"><input name="holder_name" required/></Field><Field label="Fonction"><input name="holder_role"/></Field></div><div className="admin-form-row"><Field label="Service"><input name="service_name" required/></Field><Field label="Département"><input name="department"/></Field></div><div className="admin-form-row"><Field label="Numéro (automatique si vide)"><input name="card_number"/></Field><Field label="Valide jusqu’au"><input name="valid_until" type="date"/></Field></div><Field label="URL de la photo"><input name="photo_url" type="url"/></Field></Form>}
      {dialog==="mail"&&<Form title="Nouveau message" onSubmit={e=>submit(e,sendEmailAction)} pending={pending}><Field label="Destinataire"><input name="recipient" type="email" required/></Field><Field label="Objet"><input name="subject" required/></Field><Field label="Message"><textarea name="body" rows={8} required/></Field></Form>}
      {dialog==="conversation"&&<Form title="Nouvelle discussion" onSubmit={e=>submit(e,createConversationAction)} pending={pending}><Field label="Type"><select name="conversation_type"><option value="project">Discussion liée à un projet</option><option value="direct">Message privé</option><option value="group">Groupe de discussion</option></select></Field><Field label="Nom de la discussion"><input name="title" placeholder="Ex. Comité de pilotage"/></Field><Field label="Projet associé"><select name="project_id"><option value="">Aucun</option>{projects.map(project=><option value={project.id} key={project.id}>{project.name}</option>)}</select></Field><fieldset className="conversation-members"><legend>Participants</legend>{users.filter(item=>item.id!==currentUserId&&item.role!=="visiteur").map(item=><label key={item.id}><input type="checkbox" name="member_ids" value={item.id}/><span>{item.full_name}<small>{item.role}</small></span></label>)}</fieldset></Form>}
    </div></div>}
  </div>;
}

function PanelHead({title,subtitle,action,onClick}:{title:string;subtitle:string;action?:string;onClick:()=>void}){return <header><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button onClick={onClick}>+ {action}</button>}</header>}
function Empty({text}:{text:string}){return <div className="admin-empty-card"><strong>{text}</strong></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="admin-field"><span>{label}</span>{children}</label>}
function Form({title,onSubmit,pending,children}:{title:string;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;pending:boolean;children:React.ReactNode}){return <form onSubmit={onSubmit}><header><span>ABA · OPERATIONS</span><h2>{title}</h2><p>Complétez les informations puis enregistrez.</p></header><div className="admin-form-body">{children}</div><footer><button className="admin-primary-button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer"}</button></footer></form>}
